# Generated by Django 2.2.2 on 2019-06-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('order_id', models.CharField(max_length=10)),
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_desc', models.CharField(max_length=5000)),
                ('update_time', models.TimeField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
