# Generated by Django 2.2.2 on 2019-07-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
