# Generated by Django 2.2.2 on 2019-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(default=0, max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
