# Generated by Django 2.2.2 on 2019-07-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
